language: python

services:
  - postgresql

addons:
  postgresql: "9.6"

python:
  - "2.7"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

install:
  - pip install -r requirements.txt

script:
  - python run_tests.py

after_success:
  if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then coveralls; fi
