language: python

services:
  - postgresql

addons:
  postgresql: "9.6"

python:
  - "2.7"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

install:
  - pip install -r requirements.txt

script:
  - python run_tests.py

after_success:
  if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then coveralls; fi

deploy:
  provider: testpypi
  user: vinc.py
  password:
    secure: D3Q53PAY7xrR0CfiIjSpxXgIPZIQjErNqVW85/g1EjbPyF1ZeEY2UJ/stIWPhZyO+vpn8XQTtHSv441sLG/F6nuJthVbUUjtVnKCESjqDlfmb8Es+9idgymceYyX4OHvEzzMvx1cPvBsnMGiIgUelnGnp/ADXpdAB/Ii1iGgLSYtv1qCg9YAYfiZrVRyv6I2X9WVvbXmri2W6EddObLh/LHEVRCVtxUJT2/AJjGBU4ewxr44jpaY5t5XGfPWMCChD+lUKlAPHuE1haV8nMlCdgVbspTgWlVjuINQ9rnPGiSDUh37bnP7zedJG7cBzJrJvCUJBlNVcKRQywcO6fwvh0j4id3e3RMABVYszzIdkzpexWCYJg5XqEGto0zgRQfKXAz87BoSZR6v+imqy238IKt5/bhvJ9qmhi1DmPcH13YrjBRJLu3gEyseXIkJ6zSoO1kg7bIZFS6aBrohoGOKoC/aj6O/OScxfu/VBFqGsjwHOH1TAT8vVshiTKL/pqFeT/wkVXwf+5eYRhMZyQi3IpfOYjegDQnLqauAFja3o16K/FpQWBPnas3ewJuGwcRWUqFd5nhJLqmaR+7ZK2tq/nyJtMOEk4lu31U21pdAssc5CdOFIR7ZZZJz6a30MeSGB8GRlx8LwlVqqzuC469uGOy0ZZSA6fkbr8ydy3sZaw8=
  on:
    branch: master
