language: python

services:
  - postgresql

before_install:
  - sudo touch /.dockerenv

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

env:
  postgresEndpoint: "localhost:5432"

python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

install:
  - pip install -r requirements.txt

script:
  - python run_tests.py --batch

after_success:
  if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coveralls; fi

deploy:
  provider: pypi
  user: lmg-buildbot
  password:
    secure: Z7RlvMs0chA90WVqlo9WKtV8xsmOLE4vGQ2yaudtzjPNmKumlttq/t6dLK4tyxJI4vEFVV+55v9D/KW0fIyIbnvEHRFTqXT6kX1/81NHzpcUYTikzf6h4S/Nm9B/8tT8ZR2JpLnySq0ouJoI0HqgUQ1aVo4B9/yCOJhU9jyorQHKezwCJl5q2YWs2LgfU78NtJ78Pq1iGqZlZ734gS2R3JVIt4dgy/bIyjSn4twS4rwT3Z8l0bkvCEALyCAMoVOq1hjNlFRCAGnkjo3lBldCWFdJkxzJ6mY4Vo7YVWBzOi6GnpYQzaEoszS3onP0ovuqp68lS+F1y2POV/taEluQHRpNXkWW2ihZCDM88ArCZ5zXybZk7Ke0rwG5KqQPi1GEbjY7TcMDE0QjH++/SJg3Z/T2RWema3iThNkfZZ762d4AZ5blOKoVO5ouyHgcKAOA7YUOz+GOh7BezuyW/FhDIXhrbU9X0z2b9vVJ2v0N8RnDD59P7xI6qsE/4FQpbYOCo586Au7Uyl03ZY+J7v0fOAEuXmN0s8M65agvTJDP9Os3YBuUOKcjkTACd+X1asJa2ILcx3W4tXeXKHUZ/tFIXZY6dq0yr8w/UHri/yrIbsgJ/Xu1se7Pkwzl7RdLbDZ/rfM/pHVHd0ElgwfoYzS52he35Xfw1y6HyjHC7bXcBIA=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION == 3.6
